### ISSUE TITLE
Document how to run tests

### ISSUE THREAD

**Issue by mkcor** [stan-dev/pystan-next#1]
Dear @ariddell,

Newcomers would welcome a "Setup" section in the README. I have followed these steps to install the version I'm also hacking on:
```bash
$ conda create -n pystan-next python=3.6 numpy scipy cython -c conda-forge
$ source activate pystan-next
$ pip install -r test-requirements.txt
$ pip install -e .
```
But I couldn't run the test suite successfully. Running
```bash
$ python -m pytest
```
gave OS errors related to servers and processes (`[Errno 98] Address already in use`).
I haven't dived into the internals, I would like to work on https://github.com/stan-dev/pystan/issues/338#issuecomment-355820310 directly!

Thank you,
Marianne

**Comment by ariddell** [comment]
It looks like style checking (and type checking with mypy) is already setup on stan-dev/httpstan, which is a package upon which pystan(-next) depends. Would that do the trick here?

**Comment by mkcor** [comment]
Hi @ariddell,

I think that, to avoid confusion and for the sake of good management, we should discuss style checking in the original, dedicated issue (https://github.com/stan-dev/pystan/issues/338).

I opened this new issue to discuss running the test suite of this package (stan-dev/pystan-next). Would you have any helpful tip regarding this issue?

I just tried running the test suite of stan-dev/httpstan and I got this error: `ModuleNotFoundError: No module named 'httpstan.compile'`; should I open an issue under stan-dev/httpstan?

Thank you,
Marianne

**Comment by ariddell** [comment]
Building ``httpstan`` requires some code generation (via cython and protobuf) so it's harder to build with one command. You should be able to run the flake8 and mypy tests (which are run in .travis.yml) with:

``
tox -eflake8
tox -emypy
```

and you can do the same thing here with pystan-next too. (It should pass both.)

I'll add a .travis.yml here after I release httpstan 2.17.1.

**Comment by mkcor** [comment]
Great! Thank you, @ariddell. I had to create virtualenvs in order to use `tox`--I originally created conda envs, which I have been favouring lately (I'm influenced by @jakevdp; read [this](https://jakevdp.github.io/blog/2016/08/25/conda-myths-and-misconceptions/), for example, if you're interested).

What's blocking me at the moment is that I can't `pip install httpstan==0.2.4` (in spite of https://pypi.python.org/pypi/httpstan/0.2.4, pip only finds version 0.2.3)... *confused*

Are you going to be at StanCon?

**Comment by ariddell** [comment]
Are you on OS X? I haven't gotten around to building httpstan OS X
wheels. I can do that sooner rather than later.

Not at StanCon, unfortunately.

**Comment by mkcor** [comment]
No, I run GNU/Linux Ubuntu 16.04.3 LTS, kernel 4.4.0-104-generic, hardware x86_64.

> Not at StanCon, unfortunately.

Ok.

**Comment by ariddell** [comment]
Judging from https://pypi.python.org/pypi/httpstan

It looks like there are httpstan wheels available for Python 3.6 on OS X
and Linux. Can you try things in a 3.6 virtualenv?

**Comment by mkcor** [comment]
> Can you try things in a 3.6 virtualenv?

Oh, I thought I was in a python3.6 virtualenv, but it was actually a 3.5, thank you.

Now my issue is that I can't create a python3.6 virtualenv, running into https://github.com/conda/conda/issues/6026 ...

**Comment by ahartikainen** [comment]
Hi, here are some suggestions for your problem with conda.

First, try to update conda.

    conda update conda

If that is not working, the easiest way is probably to reinstall miniconda (or Anaconda). At least that is usually the fastest option. If you have many conda environments, (that have some non-normal components, weird packages etc.)) then I suggest that you do 
    
    pip freeze

and / or

    conda list --export

The latest versions of the conda handle the PATH and other internal stuff better.

**Comment by mkcor** [comment]
By the way, I guess by

> I'll add a .travis.yml here after I release httpstan 2.17.1.

you meant "... **Stan** 2.17.1"?

**Comment by mkcor** [comment]
Thanks for your support, @ahartikainen. I have uninstalled miniconda altogether.
Since my Ubuntu version is 16.04, I have installed python3.6 from the deadsnakes PPA.
Now I find myself with:
```bash
marianne@...:~$ python3.6 -m venv ~/.virtualenv/pystan3
Error: Command '['/home/marianne/.virtualenv/pystan3/bin/python3.6', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.

marianne@...:~$ virtualenv --python=python3.6 ~/.virtualenv/pystan3
Running virtualenv with interpreter /usr/bin/python3.6
Using base prefix '/usr'
New python executable in /home/marianne/.virtualenv/pystan3/bin/python3.6
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 2363, in <module>
    main()
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 719, in main
    symlink=options.symlink)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 942, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 1261, in install_python
    shutil.copyfile(executable, py_executable)
  File "/usr/lib/python3.6/shutil.py", line 104, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/usr/bin/python3.6' and '/home/marianne/.virtualenv/pystan3/bin/python3.6' are the same file
```

So Python 2.7 packages seem to be interfering (which I have found reported here and there, so I tried updating various packages, to no avail).

**Comment by mkcor** [comment]
Thank you so much for your help, @ahartikainen! I uninstalled miniconda altogether and was able to create a python3.6 virtualenv, wherein I was able to pip install httpstan 0.2.4!

**Comment by mkcor** [comment]
@ariddell @ahartikainen So, I went down a rabbit hole with `httpstan` and concurrency and coroutines and event loops and async I/O over HTTP... :rabbit2:

Let's consider a single test:

```bash
$ python -m pytest tests/test_normal.py::test_normal_compile
```

Assuming we take care of freeing up port 8080 (initial `OSError` I faced), I'm blocked at this point:
https://github.com/stan-dev/pystan-next/blob/master/pystan/httpstan_helpers.py#L39-L40

Please find below some debugging information:

```py
(Pdb) resp
<ClientResponse(http://localhost:8081/v1/models) [500 Internal Server Error]>
<CIMultiDictProxy('Content-Type': 'text/html; charset=utf-8', 'Content-Length': '141', 'Date': 'Fri, 12 Jan 2018 01:56:34 GMT', 'Server': 'Python/3.6 aiohttp/2.3.7', 'Connection': 'close')>

(Pdb) resp.status
500
```

Could you enlighten me on why the POST request to `http://localhost:8080/v1/models` is failing?

**Comment by ariddell** [comment]
I'm getting a segfault when i run ``python3 -m pytest -v tests/test_normal.py::test_normal_sample``.

httpstan has its tests passing and pystan(-next) should be nothing more than a thin client for interacting with httpstan. But clearly there's something going wrong here.

Sorry there isn't an easier place to dig in.

**Comment by ahartikainen** [comment]
The problem is probably the `can't start a new thread`. (The thread limit on Linux machines is 10k and on mac 1k, source test with my mac and google)

In `pystan/model.py` these lines (80-81) should be flipped:

    async for payload_response in httpstan_helpers.post_aiter(host, port, path, payload):
        with tqdm.tqdm(total=pbar_total) as pbar:

to

    with tqdm.tqdm(total=pbar_total) as pbar:
        async for payload_response in httpstan_helpers.post_aiter(host, port, path, payload):

Then `tqdm` will not create a new progress bar for each sample (and create a new thread).

After this is fixed sampling goes ok, but with large sample counts (`num_samples` > ~5000) it fails to get all the samples (fails in fit class - `assert draw_index == num_samples_saved`). Not sure if there is a timeout or something else.

**Comment by mkcor** [comment]
Thanks for following up, @ariddell and @ahartikainen! I have synced up my fork with your changes since the initial commit.

It seems that I am now getting an error upon invoking GCC (see below). Any idea? I'm providing the version of my C++ compiler after this error message. Thank you!

```bash
(pystan3) marianne@...:~/python/pystan-next(master)$$ python -m pytest tests/test_normal.py::test_normal_sample
============================================================ test session starts ============================================================
platform linux -- Python 3.6.4, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
rootdir: /home/marianne/python/pystan-next, inifile:
collected 1 item                                                                                                                            

tests/test_normal.py F                                                                                                                [100%]

================================================================= FAILURES ==================================================================
____________________________________________________________ test_normal_sample _____________________________________________________________

    def test_normal_sample():
        """Sample from normal distribution."""
        program_code = 'parameters {real y;} model {y ~ normal(0,1);}'
>       posterior = pystan.compile(program_code, data={})

tests/test_normal.py:14: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pystan/model.py:113: in compile
    response_payload = requests.post(f'http://{host}:{port}{path}', data=payload).json()
../../.virtualenv/pystan3/lib/python3.6/site-packages/requests/models.py:892: in json
    return complexjson.loads(self.text, **kwargs)
/usr/lib/python3.6/json/__init__.py:354: in loads
    return _default_decoder.decode(s)
/usr/lib/python3.6/json/decoder.py:339: in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <json.decoder.JSONDecoder object at 0x7f8a35ddaa90>
s = '<html><head><title>500 Internal Server Error</title></head><body><h1>500 Internal Server Error</h1>Server got itself in trouble</body></html>'
idx = 0

    def raw_decode(self, s, idx=0):
        """Decode a JSON document from ``s`` (a ``str`` beginning with
            a JSON document) and return a 2-tuple of the Python
            representation and the index in ``s`` where the document ended.
    
            This can be used to decode a JSON document from a string that may
            have extraneous data at the end.
    
            """
        try:
            obj, end = self.scan_once(s, idx)
        except StopIteration as err:
>           raise JSONDecodeError("Expecting value", s, err.value) from None
E           json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

/usr/lib/python3.6/json/decoder.py:357: JSONDecodeError
----------------------------------------------------------- Captured stdout setup -----------------------------------------------------------
======== Running on http://127.0.0.1:8080 ========
(Press CTRL+C to quit)
----------------------------------------------------------- Captured stdout call ------------------------------------------------------------
Compiling /tmp/tmp3x8kk28h/model_9eed7dc3bb9f8485d78a41db4458372949e91a5ba554d80c52ad8fc40369a2c1.pyx because it changed.
[1/1] Cythonizing /tmp/tmp3x8kk28h/model_9eed7dc3bb9f8485d78a41db4458372949e91a5ba554d80c52ad8fc40369a2c1.pyx
----------------------------------------------------------- Captured stderr call ------------------------------------------------------------
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/tmp/tmp3x8kk28h/model_9eed7dc3bb9f8485d78a41db4458372949e91a5ba554d80c52ad8fc40369a2c1.cpp:58:20: fatal error: Python.h: No such file or directory
compilation terminated.
web_protocol.py            352 ERROR    Error handling request
Traceback (most recent call last):
  File "/home/marianne/.virtualenv/pystan3/lib/python3.6/site-packages/httpstan/views.py", line 72, in handle_models
    module_bytes = await httpstan.cache.load_model_extension_module(model_id, request.app['db'])
  File "/home/marianne/.virtualenv/pystan3/lib/python3.6/site-packages/httpstan/cache.py", line 101, in load_model_extension_module
    raise KeyError(f'Extension module for id `{model_id}` not found.')
KeyError: 'Extension module for id `9eed7dc3bb9f8485d78a41db4458372949e91a5ba554d80c52ad8fc40369a2c1` not found.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/usr/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marianne/.virtualenv/pystan3/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 410, in start
    resp = yield from self._request_handler(request)
  File "/home/marianne/.virtualenv/pystan3/lib/python3.6/site-packages/aiohttp/web.py", line 325, in _handle
    resp = yield from handler(request)
  File "/home/marianne/.virtualenv/pystan3/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 93, in impl
    return (yield from handler(request))
  File "/home/marianne/.virtualenv/pystan3/lib/python3.6/site-packages/httpstan/views.py", line 75, in handle_models
    module_bytes = await httpstan.models.compile_model_extension_module(program_code)
  File "/home/marianne/.virtualenv/pystan3/lib/python3.6/site-packages/httpstan/models.py", line 88, in compile_model_extension_module
    module_bytes = _build_extension_module(model_id, cpp_code, pyx_code_template)
  File "/home/marianne/.virtualenv/pystan3/lib/python3.6/site-packages/httpstan/models.py", line 220, in _build_extension_module
    build_extension.run()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/usr/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
------------------------------------------------------------- Captured log call -------------------------------------------------------------
connectionpool.py          208 DEBUG    Starting new HTTP connection (1): localhost
connectionpool.py          396 DEBUG    http://localhost:8080 "POST /v1/models HTTP/1.1" 500 141
========================================================= 1 failed in 3.02 seconds ==========================================================
```

About my C++ compiler:
```bash
(pystan3) marianne@...:~/python/pystan-next(master)$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.5' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)
```

**Comment by ariddell** [comment]
@mkcor @ahartikainen Please forgive me for this mess. httpstan is a working prototype but pystan-next probably shouldn't be public yet. I need to experiment some more to figure out how have pystan-next start and stop its background httpstan server.

There isn't that much work to do here. With luck I'll have some time to work on this soon.

**Comment by mkcor** [comment]
@ariddell Okay, then I'll hold off until further notice. I'll stick with PyStan 2 for now!

**Comment by ahartikainen** [comment]
Ok,

One thing I noticed was that the `localhost` on docker is not the same thing as in normal os. Not sure what it was supposed to be but something like `0.0.0.0`. So maybe add "hidden" option to define ip + port. This could enable things to run on external servers, with https or ssh.

**Comment by ariddell** [comment]
@ahartikainen My idea was to do that with environment variables in the case of pystan. HTTPSTAN_PORT and HTTPSTAN_HOST. In httpstan one would also be able to use command-line flags. I've created an issue: https://github.com/stan-dev/httpstan/issues/40
