### ISSUE TITLE
Require xarray, drop pandas from documentation

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/pystan-next#103]
Pandas is a huge requirement (10.2 MB). xarray is 0.7MB, 14 times smaller. We can safely require xarray and eliminate the confusing situation that exists right now. (Right now we talk about `.to_frame` but do not require pandas.)

**Comment by ahartikainen** [comment]
I think xarray needs netcdf4, what is the size for it?

PyMC4 probably goes with ArviZ InferenceData solution. There is always an option to do something similar, if needed.

**Comment by riddell-stan** [comment]
Actually, it looks like xarray requires pandas, <https://github.com/pydata/xarray/blob/master/requirements.txt>.
