### ISSUE TITLE
Rename (temporarily?) to pystan3?

### ISSUE THREAD

**Issue by defjaf** [stan-dev/pystan-next#115]
Would it be possible to rename the package (at least for now, while it is not the release version) to pystan3? That would enable coexistence with the current non-beta branch. (I understand that is already possible with a virtual environment.)

**Comment by ahartikainen** [comment]
I think we will move this under `stan` package.

**Comment by riddell-stan** [comment]
We're following semantic versioning too. This all follows widely-accepted practice in the Python world.

**Comment by defjaf** [comment]
Apologies, but I admit I don't understand the responses! The goal of my question is to be able to test and run the dev version of pystan (3) along with the main non-beta version.

**Comment by riddell-stan** [comment]
No problem @defjaf . I'd propose posting a question on the Stan forum https://discourse.mc-stan.org . (This is a place for bug reports.) On the forum, someone will no doubt provide a description of how to set up two different `venv`s using the Python `venv` module.
