### ISSUE TITLE
Need to installing pandas separately not indicated in documentation

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/pystan-next#124]
Users will need to install pandas themselves if they want to use `fit.to_frame`. This needs to be indicated in the documentation.

A separate issue: We may also want to allow users to do something like `pip install pystan[full]` in order to get pandas. But this seems hardly worth it when it is only one package.

**Comment by ahartikainen** [comment]
When we update conda-forge I think we can add pandas and arviz.

Getting that `pystan[full]` to work should be easy.
