### ISSUE TITLE
Model build with empty data segfaults

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/pystan-next#137]
This causes some building step to segfault

```
In [1]: import stan

In [2]: program_code = """data {int N;} parameters {vector[N] y;} model { y ~ normal(0,1); }"""

In [3]: posterior = stan.build(program_code, data={})
Segmentation fault
```

```
>>> stan.__version__
'3.0.0-beta.1'
>>> httpstan.__version__
'2.0.4'
```

**Comment by riddell-stan** [comment]
This should be easier to debug once https://github.com/stan-dev/httpstan/issues/390 is addressed. `gdb` should tell us what is going wrong.

**Comment by riddell-stan** [comment]
I think I've found the bug. I believe it's in the stanc3 generated code. I'm working on figuring out a way to produce a test case for the stanc3 devs.
