### ISSUE TITLE
[discussion] PyStan 3 Beta 2 and Proposed PyStan 2 Deprecation Plans

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/pystan-next#140]
This is a draft of a post intended for the Stan Forums. Feedback welcome. It would be nice to find some kind of common ground among the PyStan devs and among any other Stan devs who care to sign on.

# PyStan 3 Beta 2 and Proposed PyStan 2 Deprecation Plans

PyStan 3 Beta 2 is here and it works for most people. It uses Stan 2.24.0 and has great features PyStan 2 lacks. A release candidate for PyStan 3 will wait until RStan 3 is ready since harmonizing the interfaces is a high-priority goal.

PyStan 2 works fine but is stuck on 2.19. It is fair to say that PyStan 2 is no longer actively maintained.

This leaves us in an uncomfortable situation. PyStan 2 is not maintained but there is no official, non-beta-version replacement for PyStan 2. (And there will be no official replacement until RStan 3 is ready.) This post describes one proposed way of dealing with this situation.

-----

People who can move to PyStan 3 Beta 2 should start doing so. For those using the default sampler, PyStan 3 Beta 2 works fine. If you can draw samples using code written for PyStan 2, you can very likely draw samples using PyStan 3 Beta 2.

As for people who can't move to or who depend on features missing from PyStan 3 Beta 2, there are some alternatives available.

People who can start using PyStan 3 Beta 2 right now:

- macOS and Linux users who have x86_64 hardware and who are drawing samples from models using the default sampler.

People who cannot start using PyStan 3 Beta 2 right now:

- Users who use variational inference, maximization algorithms (e.g., LBFGS), or samplers other than the default sampler.
- Users stuck on Python 2.
- Windows users who cannot use WSL2 to emulate Linux.

For these users it makes sense to switch over to a different Stan interface (e.g., CmdStanPy, CmdStan, RStan) or use a different NUTS implementation (e.g., PyMC3). PyStan 3's set of supported platforms is unlikely to change before 2021. People using Stan for VI or posterior maximization can use packages such as jax and pytorch. jax and pytorch support a broader range of optimization algorithms. They also have multinational corporations supporting their development.

------
It seems to me that there's a path available for all Python users who want to use newer versions of the Stan C++ library. No Python user is left entirely without options.

With this in mind, I'd like to propose doing the following over the coming months:

1. Announce PyStan 3 Beta 2 in a variety of places in order to attract more testers.
2. Indicate in a variety of places that PyStan 2 is no longer being developed and that folks should start exploring their options.

Updated 2020-08-19: Minor edits for style, changed WSL to WSL2.
Updated 2020-08-31: Minor edits in last section.

**Comment by riddell-stan** [comment]
cc @ahartikainen

**Comment by ahartikainen** [comment]
### maximum likelihood

> MAP estimation

I think Stan does not do MAP, but penalized maximum likelihood; but really, not important

### WSL

> Windows users who cannot use WSL to emulate Linux.

I would transform "WSL" to "WSL/WSL2 or Docker"

### Jupyter

There is an interface problem with the Jupyter users (not sure about Spyder/PyCharm),

I created this https://pypi.org/project/pystan-jupyter/
But is alpha/beta/whatever one wants to call it, and mostly created for me.
In future, there are probably better solutions to that problem.

### PyStan2

For current PyStan2, I have thought that we should probably revert the latest Stan upgrade (2.22) on develop.

**Comment by riddell-stan** [comment]
> I would transform "WSL" to "WSL/WSL2 or Docker"

What's the difference between WSL and WSL2? Are there WSL users who can't use WSL2? I don't think we need to mention Docker -- if we did we should also mention KVM, Xen, Virtualbox, etc, and all the other virtualization options.

> For current PyStan2, I have thought that we should probably revert the latest Stan upgrade (2.22) on develop.

PyStan 2 (using Stan 2.22) requires building from source. We have been consistent in the past about providing wheels for people. I'm not certain it would be a good idea to encourage people to start installing from source. It might create a lot of support requests.

> Jupyter

You're right that we need to post instructions on how to do the workaround somewhere. I'll check that pinning tornado fixes the problem.

**Comment by riddell-stan** [comment]
Sorry, I might have misunderstood the PyStan 2 question. Did you want to revert 2.22 back to 2.19? Or did you want to release PyStan 2.22 wheels?

**Comment by ahartikainen** [comment]
Revert to 2.19

**Comment by riddell-stan** [comment]
re: schedule for beta 2: I've tagged the beta 2 issues in httpstan and 
pystan-next. I'd like to resolve those issues first.

**Comment by riddell-stan** [comment]
@ahartikainen I've edited the draft to incorporate your corrections. Shall I say this document represents both our views? We can also highlight disagreements if there are any.

**Comment by riddell-stan** [comment]
@ahartikainen Any last minute changes? If I don't hear from you I'll post this tomorrow.

**Comment by ahartikainen** [comment]
Oh, I forgot to comment. I'm happy with the message.

**Comment by riddell-stan** [comment]
Posted https://discourse.mc-stan.org/t/pystan-3-beta-2-and-proposed-pystan-2-deprecation-plans/17833
