### ISSUE TITLE
Iterating over an instance of `Fit` raises AttributeError.

### ISSUE THREAD

**Issue by omarfsosa** [stan-dev/pystan-next#142]
Instances of `stan.fit.Fit` have a `__getitem__` method and a `__len__` method. But iterating over them will raise a weird AttributeError: 
```
AttributeError: 'int' object has no attribute 'endswith'
```

Given how `len`  and `__getitem__` work,  I think __iter__ should scan through the names of the parameters.

Perhaps there is a good reason for not making a fit object be iterable, in which case I think `__iter__` should raise a `TypeError` instead:

```
TypeError: 'stan.fit.Fit' object is not iterable
```

**Comment by riddell-stan** [comment]
This sounds good to me. An instance of Fit should behave a bit like a dict.

**Comment by ahartikainen** [comment]
Should we add then `.keys`, `.items`, `.values` or should iteration return `key, values`?

**Comment by riddell-stan** [comment]
The `fit` feels dict-like to me. So iteration would return keys.
