### ISSUE TITLE
Manual caching

### ISSUE THREAD

**Issue by hugbubby** [stan-dev/pystan-next#143]
With pystan2, you can compile a model and pickle it without actually fitting it to data and/or generating samples. I needed this discretion in how models were cached and reused, because in my case the service that fits the models and provides a web service for accessing them doesn't have the RAM to compile them. Until I have a mechanism for compiling a model on one computer and deploying it on another I can't upgrade to pystan3, as nice as the new model caching mechanism might be.

**Comment by ahartikainen** [comment]
This issue belongs to httpstan which does the caching.

**Comment by ahartikainen** [comment]
See https://github.com/stan-dev/httpstan/blob/main/httpstan/cache.py

With those functions you can find the directory for cached model files, and you can see the name of the model from the model object.

I have not tested if this works (compile on one computer and use it on another), but let's us know how it works out for you.

**Comment by hugbubby** [comment]
Here's the thing: I don't even want the dev laptops that compile this model to have access to the data used to train it, for security reasons. I suppose I could put in an empty pseudo-dataset, but that seems like it might be hacky.

**Comment by riddell-stan** [comment]
I think you may be OK. The data itself is never saved or cached anywhere. We cache the model (i.e., the compiled Stan program) and then any fits (i.e., the posterior draws).

**Comment by hugbubby** [comment]
The data is pulled from a remote service with a token. The credentials themselves, required to access the training data, are the issue here, not the caching. If they can grab the data for the purpose of compiling the model they can also just modify the script and write it to disk. I could create a specific service for compiling and downloading stan models with tightened scope and more specific access control measures, but that'd be work ;p.

**Comment by ahartikainen** [comment]
If you are not needing to run the model, use fake data?

`numpy.random.randn`/`numpy.random.rand` can create ndimensional arrays easily.

**Comment by riddell-stan** [comment]
I think I understand this. This isn't about caching but the requirement 
to provide data when compiling, right?

We probably do need to deal with model pre-compilation at some point. 
Providing random data is a bit of a hack.

In the very short term I would suggest that this hack gets documented on 
the forum. It solves the problem for the small set of users who really 
need to not provide data during compilation.

**Comment by ahartikainen** [comment]
> We probably do need to deal with model pre-compilation at some point.

How could we do this without too much of code-duplication.

> Providing random data is a bit of a hack.

Yes

**Comment by riddell-stan** [comment]
Closing for now since this doesn't appear to be about caching and the random data trick solves the problem.
