### ISSUE TITLE
Build once, use many times

### ISSUE THREAD

**Issue by IvanUkhov** [stan-dev/pystan-next#172]
Hello,

In PyStan 2, it is possible to compile the model only once, pickle it, and then fit it to multiple data sets, which saves a lot of time. How to achieve the same in PyStan 3? I see `data` is now part of `build`. Thank you!

**Comment by riddell-stan** [comment]
This all happens automatically now.

**Comment by IvanUkhov** [comment]
Oh, this is great! Thank you!

**Comment by defjaf** [comment]
Just to clarify, "it all happens automatically now" means that it uses the cached model so the compilation step of `build` is free after the first time, correct? (I admit that my mental model fit better with the old interface!)

**Comment by ahartikainen** [comment]
Yes.

Internally (@riddell-stan please correct me if needed here)

1. (pystan) Stan-code -> 
2. (httpstan) Stan-code -> 
3. (httpstan internal)  C++ -code -> 
4. (httpstan internal; check cache) executable -> 
5. (httpstan) executable + seed for PRNG -> 
6. (user interface) model

(not the best terminology)

**Comment by riddell-stan** [comment]
@defjaf Do you have suggestions for making things more explicit in the documentation? We could certainly add information to the `build` docstring.

We could also add a section about caching to the Upgrading from PyStan 2 document.

**Comment by defjaf** [comment]
@riddell-stan I think you should at the very least explicitly say something like: "to run the same model with new data, just use `build` again. Because `pystan` caches the model after compilation, that time-consuming step will not be necessary unless the model changes."

Certainly this should also go in the upgrading doc!
