### ISSUE TITLE
Missing `write_array` and `transform_inits` methods

### ISSUE THREAD

**Issue by mjcarter95** [stan-dev/pystan-next#175]
`Model` instances should make the `write_array` and `transform_inits` methods available. `write_array` allows users to transform unconstrained parameters to their defined support (the same as `constrain_pars` in PyStan 2), conversely `transform_inits` transforms parameters from their defined support to unconstrained space (the same as `unconstrain_pars` in PyStan 2). This would require work in `httpstan`.

**Comment by riddell-stan** [comment]
One of PyStan's few goals is having an interface which resembles RStan's. So I think for now it makes sense to mirror the functions that RStan (and PyStan 2) use. I believe these functions are constrain_pars and unconstrain_pars. See https://github.com/stan-dev/rstan/blob/develop/rstan/rstan/man/stanfit-method-logprob.Rd for the RStan docs.

Would this work?

**Comment by mjcarter95** [comment]
Yes, that works - I think that `constrain_pars` calls the `write_array` method in the model, and `unconstrain_pars` calls the `transform_inits` method of the model.

**Comment by riddell-stan** [comment]
Sounds like a good plan.

Now, for the details. For httpstan, since constrain_pars and 
unconstrain_pars do not exist in the model and we are free to align 
ourselves better with Stan C++, let's expose write_array and 
transform_init there.

**Comment by mjcarter95** [comment]
Cool. I'm close to having a pull request ready for `grad_log_prob` (just needs a test writing), will finish that up then work on this.

**Comment by riddell-stan** [comment]
@mjcarter95 we can close this, right?

**Comment by mjcarter95** [comment]
Yes, this is dealt with by `contrain_pars` and `unconstrain_pars` respectively.
