### ISSUE TITLE
Close connection if Exception is raised

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/pystan-next#3]
Currently, the shutdown procedure is not called if model_string is invalid. This keeps the port (8080) locked.

    import pystan
    model_string = "parameters {vector y;} model {y ~ cauchy(0,1);}"
    program = pystan.compile(model_string, {})
    # AssertionError is raised

    model_string2 = "parameters {vector[10] y;} model {y ~ cauchy(0,1);}"
    program2 = pystan.compile(model_string2, {})
    # OSError is raised 
    # OSError: [Errno 48] error while attempting to bind on address ('127.0.0.1', 8080): address already in use

One solution is to add `try-finally` blocks for `post` and `post_aiter` functions.

**Comment by ariddell** [comment]
Good catch!

I was thinking it might be easier for people to understand what is going on if we can keep asyncio out of pystan (that is, keep it only in httpstan). If httpstan can be run in a thread in the background it might be possible to simplify the code here a great deal.

**Comment by ariddell** [comment]
It looks like aiohttp just introduced recently some changes which might make things much easier:

I'm not sure if the docs are live yet. Here's the relevant bit:

https://github.com/aio-libs/aiohttp/blob/d86a047c08a9c581d9a84c13c0bdc9eeaf786f3d/docs/web_advanced.rst#application-runners
