### ISSUE TITLE
Missing informative __repr__ for Fit instances

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/pystan-next#41]
Following the conventions of `pandas` or `sklearn` seems like it would be a good idea here.

**Comment by ahartikainen** [comment]
Something similar as xarray?

**Comment by riddell-stan** [comment]
Yes, that sounds even better.

**Comment by riddell-stan** [comment]
Here's an example of what xarray does with repr:

```
In [4]: data = xr.DataArray(np.random.randn(2, 3),
   ...:                     dims=('x', 'y'),
   ...:                     coords={'x': [10, 20]})
   ...: 

In [5]: data
Out[5]: 
<xarray.DataArray (x: 2, y: 3)>
array([[ 0.276, -1.087, -0.674],
       [ 0.114, -1.478,  0.525]])
Coordinates:
  * x        (x) int64 10 20
Dimensions without coordinates: y
```

But a `Fit` instance is really a bundle of things like `DataArray`s, each with varying dimensions (and someday of varying draw counts).

Any thoughts here @ahartikainen ? Maybe we should look at what something like Feather or NetCDF uses as their `repr`.

**Comment by ahartikainen** [comment]
Have you seen latest html_repr for xarray?

https://twitter.com/rabernat/status/1187438606606094336?s=19

What information should we have?
Parameters - any array values, or some summary values?

Maybe some diagnostics?
Num of divergences?
max_tree_depth hits?

Where is a good balance between nothing --> full summary + diagnostics

**Comment by riddell-stan** [comment]
I'll check out the html_repr.

This is going to be `__repr__`, it needs to return instantly. I don't 
think we can do any calculations. Save those for the `summary` method.

Maybe just a list of parameters, their dimensions, and the number of 
draws for each. Would be nice if we could figure out the dtype (int or 
float).

**Comment by ahartikainen** [comment]
I think model object should contain that information (for Stan3)
