### ISSUE TITLE
Missing `summary` method for Fit instances

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/pystan-next#42]
Title says it all. Much of the (ugly) code can be imported from PyStan 2.

**Comment by riddell-stan** [comment]
@ahartikainen does arviz have an equivalent of `stansummary`? I'm thinking we could use that instead of porting the ugly code from PyStan 2.

**Comment by ahartikainen** [comment]
We have `az.summary` which returns dataframe. I have been planning also a text based output and jupyter dashboard.
