### ISSUE TITLE
`stan` is an (empty) package on PyPI

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/pystan-next#58]
People may be confused and try to `pip install stan`. `stan` was claimed on Nov 18, 2018. But there seems to be nothing there. We might try sending a nice email to the owner asking for the name. The owner's name is in the `setup.py` of the (empty) package.

**Comment by ahartikainen** [comment]
There is also a possibility to ask PyPI for that name, but I'm not sure what is the correct procedure in these cases.

`pip install stan` would allow us to keep pystan (2.x) and pystan3 (3.x) separable, if that is something we want to do.

**Comment by riddell-stan** [comment]
We can ask for the name `stan`. Someone just needs to write a nice email 
to the package owner.

As for having a different package for PyStan 3, I'm not sure there's a 
good reason for this. Package isolation with virtualenv is good and 
getting better (see current discussions about __pypackage__). And I have 
no interest in maintaining an older version of pystan for longer than is 
strictly necessary. And having two packages would potentially hint that 
the two packages would be maintained separately.
