### ISSUE TITLE
Upgrading guide missing

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/pystan-next#59]
Adding an `upgrading.rst` to the docs with basic tips would, I think, be a good idea. Here's an example of a package which has an upgrading page: https://marshmallow.readthedocs.io/en/3.0/upgrading.html

**Comment by ahartikainen** [comment]
I noticed that installing with `--pre` it also installs other pre-releases. This includes e.g. numpy 1.16rc1 which is missing still some stuff, but doesn't affect our lib.
