### ISSUE TITLE
Non-ascii char in README.rst

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/pystan-next#6]
Failing to pip install from source due to non-ascii char in README.rst (python 3.6 on Ubuntu (miniconda) docker)

Could (r) work instead of ®.

**Comment by ahartikainen** [comment]
I could fix the problem by changing the locale to use UTF-8. 

Problem is that not all users know how to do that.

**Comment by ariddell** [comment]
or we can just require Python 3.7 :) https://www.python.org/dev/peps/pep-0538/

**Comment by riddell-stan** [comment]
I think the character is gone.
