### ISSUE TITLE
PyStan changes data inplace

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/pystan-next#60]
I noticed that the following loop changes data inplace.

    # in `data`: convert numpy arrays to normal lists
    for key, value in data.items():
        if isinstance(value, np.ndarray):
            data[key] = value.tolist()

Is this what we want? Because I highly doubt that deep copy would fill anyones RAM.

**Comment by riddell-stan** [comment]
Good point. We should operate on a copy.
