### ISSUE TITLE
CI: Add a basic windows test

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/pystan-next#62]
In the event that changes in mingw or Stan math solve the windows crashing bug it would be nice to have an automatic way of learning about it. Testing windows compilation and model running with mingw -- even if it fails right now -- would let us do that.

**Comment by riddell-stan** [comment]
Windows tests need to work in httpstan first. See https://github.com/stan-dev/httpstan/pull/142

**Comment by riddell-stan** [comment]
Non-sampling windows tests now pass in httpstan (I think). It should be possible to "test" pystan 3 on windows.

**Comment by ahartikainen** [comment]
After `httpstan` (0.20) is updated, all the tests should pass.
