### ISSUE TITLE
Fit could use a __len__, number of parameters

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/pystan-next#92]
If we are allowing people to do, say, ``fit["alpha"]`` and get back an array of shape (*param_dims, num_draws), then ``len(fit)`` should surely report the number of parameters, right?

@bgoodri is there an equivalent of this thing in R? Can you do a ``length(draws)`` and get the number of $-accessible attributes?

This is not, to the best of my knowledge, mentioned in https://github.com/stan-dev/stan/wiki/User-Interface-Guidelines-for-Developers

cc @ahartikainen @bgoodri

**Comment by ahartikainen** [comment]
That sounds reasonable. Do we implement `__iter__` or possibly `.keys` method?

**Comment by bgoodri** [comment]
That sounds like a good idea. Currently in RStan, the number of parameter
names would have to be accessed by length(fit@param_names) or something.
But when we go to allowing fit["alpha"] and maybe fit[1] then we need a
better way to know how many possibilities there are.

**Comment by ahartikainen** [comment]
Option 1:

    for param, values in fit.items():
        ...

Option 2:

    fit[1] == fit[fit.param_names[1]]
